"""CA & Legal service checklists (slug, title, handled-by division, documents).

These are arranged through associated professionals, so the lists are short and indicative.
"""

SERVICES = [('income-tax-return-filing',
  'Income Tax Return Filing',
  'CA Services',
  ['PAN, Aadhaar and address proof',
   'Form 16 or income proof',
   'Bank statements',
   'Investment/deduction proofs, if applicable']),
 ('tax-planning-advisory',
  'Tax Planning & Advisory',
  'CA Services',
  ['PAN, Aadhaar and address proof',
   'Latest ITR or income details',
   'Existing investment/insurance summary']),
 ('tds-return-filing',
  'TDS Return Filing',
  'CA Services',
  ['TAN details', 'Deduction and payment records for the quarter', 'Challan details']),
 ('tds-property-sale-26qb',
  'TDS on Property Sale - Form 26QB',
  'CA Services',
  ['PAN, Aadhaar and address proof', 'Sale agreement', 'PAN of buyer and seller']),
 ('gst-registration',
  'GST Registration',
  'CA Services',
  ['PAN, Aadhaar and address proof',
   'Business proof (registration certificate, partnership deed, etc.)',
   'Business address proof',
   'Bank account details']),
 ('gst-return-filing',
  'GST Return Filing & Compliance',
  'CA Services',
  ['Sales and purchase registers',
   'GST login credentials',
   'Bank statements, if required for reconciliation']),
 ('gst-reconciliation-notice-support',
  'GST Reconciliation & Notice Support',
  'CA Services',
  ['GST returns filed to date', 'Books of accounts', 'Copy of notice, if applicable']),
 ('accounting-bookkeeping',
  'Accounting & Bookkeeping',
  'CA Services',
  ['Bank statements', 'Sales/purchase invoices', 'Expense records']),
 ('tax-audit-support',
  'Tax Audit Support',
  'CA Services',
  ['Books of accounts', 'Bank statements', "Prior year's audit report, if applicable"]),
 ('company-llp-registration',
  'Company & LLP Registration',
  'CA Services',
  ['PAN, Aadhaar and address proof',
   'Registered office proof',
   'Passport-size photographs',
   'Digital Signature Certificate (DSC)']),
 ('msme-udyam-registration',
  'MSME / Udyam Registration',
  'CA Services',
  ['PAN, Aadhaar and address proof', 'Business PAN', 'Bank account and GST details, if applicable']),
 ('shop-act-fssai-registration',
  'Shop Act (Gumasta) & FSSAI Registration',
  'CA Services',
  ['PAN, Aadhaar and address proof',
   'Premises proof (rent agreement/ownership document)',
   'Business constitution proof']),
 ('pan-tan-dsc-services',
  'PAN, TAN & DSC Services',
  'CA Services',
  ['PAN, Aadhaar and address proof', "Business registration proof, for TAN/DSC in a company or firm's name"]),
 ('property-title-verification',
  'Property Title Verification & Due Diligence',
  'Sheetal Associates',
  ['Title documents/chain', '7/12 extract or property card', 'Encumbrance certificate, where available']),
 ('sale-agreement-sale-deed',
  'Sale Agreement & Sale Deed Drafting',
  'Sheetal Associates',
  ['PAN, Aadhaar and address proof', 'Property title documents', 'Previous agreement, if any']),
 ('gift-release-deed',
  'Gift Deed & Release Deed Documentation',
  'Sheetal Associates',
  ['PAN, Aadhaar and address proof', 'Property title documents', 'Proof of relationship, where relevant']),
 ('power-of-attorney-drafting',
  'Power of Attorney Drafting',
  'Sheetal Associates',
  ['PAN, Aadhaar and address proof', 'Details of the person being authorised']),
 ('society-share-transfer',
  'Housing Society Share Transfer',
  'Sheetal Associates',
  ['PAN, Aadhaar and address proof',
   'Share certificate',
   'Sale/gift/release deed as applicable',
   'Society NOC application']),
 ('society-noc-membership',
  'Society NOC & Membership Documentation',
  'Sheetal Associates',
  ['PAN, Aadhaar and address proof', 'Share certificate', 'Reason/purpose for the NOC']),
 ('sra-flat-transfer',
  'SRA Flat Transfer Documentation',
  'Sheetal Associates',
  ['PAN, Aadhaar and address proof', 'SRA allotment/agreement documents', 'Reason for transfer']),
 ('mhada-flat-transfer',
  'MHADA Flat Transfer Documentation',
  'Sheetal Associates',
  ['PAN, Aadhaar and address proof', 'MHADA allotment letter/agreement', 'Reason for transfer']),
 ('mmrda-property-documentation',
  'MMRDA Property Documentation',
  'Sheetal Associates',
  ['Allotment/agreement documents', 'Reason for the request']),
 ('society-redevelopment-documentation',
  'Society Redevelopment Documentation',
  'Sheetal Associates',
  ['Society registration documents',
   'Existing member/share documents',
   'Developer agreement, where applicable']),
 ('legal-drafting-agreements-affidavits',
  'Legal Drafting - Agreements, Affidavits & Notices',
  'Sheetal Associates',
  ['PAN, Aadhaar and address proof', 'Relevant background documents for the matter']),
 ('public-notice-publication',
  'Public Notice Publication',
  'Sheetal Associates',
  ['PAN, Aadhaar and address proof',
   'Details/proof relevant to the notice (e.g. FIR copy for a lost document, property papers for a sale '
   'notice)']),
 ('nri-property-documentation',
  'NRI Property Documentation',
  'Sheetal Associates',
  ['Passport/OCI details', 'Property title documents', 'POA, if a representative will act locally']),
 ('will-succession-documentation',
  'Will & Succession Documentation',
  'Sheetal Associates',
  ['PAN, Aadhaar and address proof',
   'Asset/property details',
   'Death certificate and family details, for succession matters'])]
