/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MumbaiRouteImport } from './routes/mumbai'
import { Route as NaviMumbaiRouteImport } from './routes/navi-mumbai'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PuneRouteImport } from './routes/pune'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ThaneRouteImport } from './routes/thane'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as CaLegalServicesIndexRouteImport } from './routes/ca-legal-services.index'
import { Route as CaLegalServicesSlugRouteImport } from './routes/ca-legal-services.$slug'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MumbaiRoute = MumbaiRouteImport.update({
  id: '/mumbai',
  path: '/mumbai',
  getParentRoute: () => rootRouteImport,
} as any)
const NaviMumbaiRoute = NaviMumbaiRouteImport.update({
  id: '/navi-mumbai',
  path: '/navi-mumbai',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PuneRoute = PuneRouteImport.update({
  id: '/pune',
  path: '/pune',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ThaneRoute = ThaneRouteImport.update({
  id: '/thane',
  path: '/thane',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CaLegalServicesIndexRoute = CaLegalServicesIndexRouteImport.update({
  id: '/ca-legal-services/',
  path: '/ca-legal-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaLegalServicesSlugRoute = CaLegalServicesSlugRouteImport.update({
  id: '/ca-legal-services/$slug',
  path: '/ca-legal-services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/mumbai': typeof MumbaiRoute
  '/navi-mumbai': typeof NaviMumbaiRoute
  '/partner': typeof PartnerRoute
  '/pune': typeof PuneRoute
  '/services': typeof ServicesRouteWithChildren
  '/thane': typeof ThaneRoute
  '/tools': typeof ToolsRoute
  '/why-us': typeof WhyUsRoute
  '/ca-legal-services/$slug': typeof CaLegalServicesSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ca-legal-services/': typeof CaLegalServicesIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/mumbai': typeof MumbaiRoute
  '/navi-mumbai': typeof NaviMumbaiRoute
  '/partner': typeof PartnerRoute
  '/pune': typeof PuneRoute
  '/thane': typeof ThaneRoute
  '/tools': typeof ToolsRoute
  '/why-us': typeof WhyUsRoute
  '/ca-legal-services/$slug': typeof CaLegalServicesSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ca-legal-services': typeof CaLegalServicesIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/mumbai': typeof MumbaiRoute
  '/navi-mumbai': typeof NaviMumbaiRoute
  '/partner': typeof PartnerRoute
  '/pune': typeof PuneRoute
  '/services': typeof ServicesRouteWithChildren
  '/thane': typeof ThaneRoute
  '/tools': typeof ToolsRoute
  '/why-us': typeof WhyUsRoute
  '/ca-legal-services/$slug': typeof CaLegalServicesSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/ca-legal-services/': typeof CaLegalServicesIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/mumbai'
    | '/navi-mumbai'
    | '/partner'
    | '/pune'
    | '/services'
    | '/thane'
    | '/tools'
    | '/why-us'
    | '/ca-legal-services/$slug'
    | '/case-studies/$slug'
    | '/services/$slug'
    | '/ca-legal-services/'
    | '/case-studies/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/mumbai'
    | '/navi-mumbai'
    | '/partner'
    | '/pune'
    | '/thane'
    | '/tools'
    | '/why-us'
    | '/ca-legal-services/$slug'
    | '/case-studies/$slug'
    | '/services/$slug'
    | '/ca-legal-services'
    | '/case-studies'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/mumbai'
    | '/navi-mumbai'
    | '/partner'
    | '/pune'
    | '/services'
    | '/thane'
    | '/tools'
    | '/why-us'
    | '/ca-legal-services/$slug'
    | '/case-studies/$slug'
    | '/services/$slug'
    | '/ca-legal-services/'
    | '/case-studies/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  MumbaiRoute: typeof MumbaiRoute
  NaviMumbaiRoute: typeof NaviMumbaiRoute
  PartnerRoute: typeof PartnerRoute
  PuneRoute: typeof PuneRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  ThaneRoute: typeof ThaneRoute
  ToolsRoute: typeof ToolsRoute
  WhyUsRoute: typeof WhyUsRoute
  CaLegalServicesSlugRoute: typeof CaLegalServicesSlugRoute
  CaLegalServicesIndexRoute: typeof CaLegalServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mumbai': {
      id: '/mumbai'
      path: '/mumbai'
      fullPath: '/mumbai'
      preLoaderRoute: typeof MumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navi-mumbai': {
      id: '/navi-mumbai'
      path: '/navi-mumbai'
      fullPath: '/navi-mumbai'
      preLoaderRoute: typeof NaviMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pune': {
      id: '/pune'
      path: '/pune'
      fullPath: '/pune'
      preLoaderRoute: typeof PuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thane': {
      id: '/thane'
      path: '/thane'
      fullPath: '/thane'
      preLoaderRoute: typeof ThaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca-legal-services/': {
      id: '/ca-legal-services/'
      path: '/ca-legal-services'
      fullPath: '/ca-legal-services/'
      preLoaderRoute: typeof CaLegalServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca-legal-services/$slug': {
      id: '/ca-legal-services/$slug'
      path: '/ca-legal-services/$slug'
      fullPath: '/ca-legal-services/$slug'
      preLoaderRoute: typeof CaLegalServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  MumbaiRoute: MumbaiRoute,
  NaviMumbaiRoute: NaviMumbaiRoute,
  PartnerRoute: PartnerRoute,
  PuneRoute: PuneRoute,
  ServicesRoute: ServicesRouteWithChildren,
  ThaneRoute: ThaneRoute,
  ToolsRoute: ToolsRoute,
  WhyUsRoute: WhyUsRoute,
  CaLegalServicesSlugRoute: CaLegalServicesSlugRoute,
  CaLegalServicesIndexRoute: CaLegalServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
